<?php

namespace Administration\AdministrationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CarteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteRepository extends EntityRepository
{
    
}
