<?php

namespace Client\ClientBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AmbianceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function findNbrUser() {

        return $this->createQueryBuilder('p')

            ->select('COUNT(p)')

            ->getQuery()

            ->getSingleScalarResult();

    }


    public function findByPremium(){
        $req = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.premiumClient like :premium')
            ->orderBy('p.id')
            ->setParameter('premium', 'active');
        return $req->getQuery()->getResult();
    }

    public function findByBloque(){
        $req = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.enabled = :bloque')
            ->orderBy('p.id')
            ->setParameter('bloque', 0);
        return $req->getQuery()->getResult();
    }

    public function findByAdmin($role){
        $req = $this->createQueryBuilder('p')
            ->select('u')
                ->from($this->_entityName, 'u')
                ->where('u.roles LIKE :roles')
                ->setParameter('roles', '%"'.$role.'"%');
        return $req->getQuery()->getResult();
    }

}
