mobile:
    resource: "@MobileBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

projet:
    resource: "@ProjetBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@ClientBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

client:
    resource: "@ClientBundle/Resources/config/routing.yml"
    prefix:   /

administration:
    resource: "@AdministrationBundle/Resources/config/routing.yml"
    prefix:   /administration

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
