<?php

namespace Client\ClientBundle\Repository;

/**
 * BloqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BloqueRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByBloque($userId){
        $req = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.fromClient = :bloque')
            ->orWhere('p.toClient = :bloque')

            ->setParameter('bloque', $userId);
        return $req->getQuery()->getResult();
    }
}
