<?php

namespace Client\ClientBundle\Repository;

/**
 * MessageRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRelationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTousMessage($user){
        $req = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.sender  = :user')
            ->orWhere('p.receiver  = :user')
            ->orderBy('p.dateMessageRelation', 'DESC')
            ->setParameter('user', $user);
        return $req->getQuery()->getResult();
    }

    public function findNombreMessage($user){
        $req = $this->createQueryBuilder('p')
            ->select('COUNT(p)')
            ->where('p.sender  = :user')
            ->orWhere('p.receiver  = :user')
            ->andWhere('p.luMessageRelation like :lu')
            ->orderBy('p.dateMessageRelation', 'DESC')
            ->setParameter('user', $user)
            ->setParameter('lu', 'active');
        return $req->getQuery()->getSingleScalarResult();
    }
}
