<?php

namespace Client\ClientBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByUser($user){
        $req = $this->createQueryBuilder('n')
            ->select('n')
            ->join('n.publication','p')
            ->where('p.client  = :user')
            ->setParameter('user', $user);
        return $req->getQuery()->getResult();
    }
}
