<?php

namespace Client\ClientBundle\Repository;

/**
 * PhotographeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotographeRepository extends \Doctrine\ORM\EntityRepository
{
}
