<?php

namespace Client\ClientBundle\Repository;

/**
 * PublicationPhotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationPhotosRepository extends \Doctrine\ORM\EntityRepository
{

}
