<?php

namespace Client\ClientBundle\Repository;

/**
 * RankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRankByUser($userId) {

        return $this->createQueryBuilder('p')

            ->select('COUNT(p)')
            ->where('p.client  =:user')
            ->setParameter('user', $userId)
            ->getQuery()

            ->getSingleScalarResult();

    }
}
