<?php

namespace Client\ClientBundle\Repository;

/**
 * SavedLieuUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SavedLieuUserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByLieu($userId){
        $req = $this->createQueryBuilder('p')

            ->select('p')
            ->join('p.etablissement','e')
            ->where('p.client  = :user')

            ->orderBy('p.dateSavedLieuUser')
            ->groupBy('p.etablissement')

            ->setParameter('user', $userId);
        return $req->getQuery()->getResult();
    }
}
