<?php

namespace Client\ClientBundle\Repository;

/**
 * SignalUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalUserRepository extends \Doctrine\ORM\EntityRepository
{

}
