<?php

namespace Projet\ProjetBundle\Repository;

/**
 * EtablissementSignalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementSignalRepository extends \Doctrine\ORM\EntityRepository
{
}
